USE UPOReuV3


----создание таблицы пользователей
CREATE TABLE LUDI (
ID_LUDI int  IDENTITY(1,1) CONSTRAINT primary_id  PRIMARY KEY,
FAMLUDI nvarchar(100) NOT NULL,
NAMLUDI nvarchar(100) NOT NULL,
OTLUDI nvarchar(100) NOT NULL,
LOGLUGI nvarchar(20) NOT NULL,
PARLUDI nvarchar(8) NOT NULL
)

INSERT INTO [LUDI]
			(
			[FAMLUDI]
			,[NAMLUDI]
			,[OTLUDI]
			,[LOGLUGI]
			,[PARLUDI])

VALUES 
			('Швец', 'Виталий', 'Викторович', 'shvec', 'parol4ik'),
			('Зубенко', 'Михаил', 'Петрович', 'mafioznik', 'pinky13g'),
			('Ума', 'Турман', 'Александровна', 'qventinloh', 'yellow')


--таблица объектов
CREATE TABLE PALAS(
ID_PALAS INT IDENTITY(1,1),
NAM_PALAS NVARCHAR(250) NOT NULL,
ADREAS_PALAS NVARCHAR(250) NOT NULL,

ID_OTVFACE INT NOT NULL,
ID_STAT_SAVE_SYS INT NOT NULL,
ID_SOS_PALASE INT NOT NULL

CONSTRAINT [PK_ID_PALAS] PRIMARY KEY CLUSTERED ([ID_PALAS] ASC) ON [PRIMARY]
)

--таблица состояния помещения
CREATE TABLE SOS_PALASE(
ID_SOS_PALASE INT IDENTITY(1,1),
NAM_SOS_PALASE NVARCHAR(250) NOT NULL,
OP_SOS_PALASE NVARCHAR(250) NOT NULL

CONSTRAINT [PK_ID_SOS_PALASE] PRIMARY KEY CLUSTERED ([ID_SOS_PALASE] ASC) ON [PRIMARY]
)

--таблица систем защиты
CREATE TABLE TYPE_SAVE_SYS(
ID_TYPE_SAVE_SYS INT IDENTITY(1,1),
NAM_TYPE_SAVE_SYS NVARCHAR(250)

CONSTRAINT [PK_TYPE_SAVE_SYS] PRIMARY KEY CLUSTERED ([ID_TYPE_SAVE_SYS] ASC) ON [PRIMARY]
)

--таблица типов технического обслуживания
CREATE TABLE TYPE_TO(
ID_TYPE_TO INT IDENTITY(1,1),
NAM_TYPE_TO NVARCHAR(250)

CONSTRAINT [PK_ID_TYPE_TO] PRIMARY KEY CLUSTERED ([ID_TYPE_TO] ASC) ON [PRIMARY]
)

--таблица комплектующих систем защиты
CREATE TABLE COM_SAVE_SYS(
ID_COM_SAVE_SYS INT IDENTITY(1,1),
NAM_COM_SAVE_SYS NVARCHAR(250) NOT NULL,
KOL_COM_SAVE_SYS NVARCHAR(10)

CONSTRAINT [PK_ID_COM_SAVE_SYS] PRIMARY KEY CLUSTERED ([ID_COM_SAVE_SYS] ASC) ON [PRIMARY]
)

--таблица состояния систем защиты
CREATE TABLE STAT_SAVE_SYS(
ID_STAT_SAVE_SYS INT IDENTITY(1,1),
NAM_STAT_SAVE_SYS NVARCHAR(250) NOT NULL

CONSTRAINT [PK_ID_STAT_SAVE_SYS] PRIMARY KEY CLUSTERED ([ID_STAT_SAVE_SYS] ASC) ON [PRIMARY]
)

--таблица вида технического обслуживания огнетушителей
CREATE TABLE TYPE_TO_OGN(
ID_TYPE_TO_OGN INT IDENTITY(1,1),
NAM_TYPE_TO_OGN NVARCHAR(250) NOT NULL,
SROK DATE

CONSTRAINT [PK_ID_TYPE_TO_OGN] PRIMARY KEY CLUSTERED ([ID_TYPE_TO_OGN] ASC) ON [PRIMARY]
)

--таблица внешнего вида огнетушителей
CREATE TABLE SOS_OGN(
ID_SOS_OGN INT IDENTITY(1,1),
SOST_OGN NVARCHAR(250) NOT NULL,
SOS_UZI NVARCHAR(250) NOT NULL,
SOS_HOD NVARCHAR(250) NOT NULL,
MASS_OGN INT NOT NULL,
DAV_OGN INT NOT NULL

CONSTRAINT [PK_ID_SOS_OGN] PRIMARY KEY CLUSTERED ([ID_SOS_OGN] ASC) ON [PRIMARY]
)

--таблица отвественных лиц
CREATE TABLE OTVFACE(
ID_OTVFACE INT IDENTITY(1,1) ,
FAM_OTVFACE NVARCHAR(250) NOT NULL,
NAM_OTVFACE NVARCHAR(250) NOT NULL,
OT_OTVFACE NVARCHAR(250) NOT NULL,
MAIL_OTVFACE NVARCHAR(250) NOT NULL,
NUM_OTVFACE NVARCHAR(15) NOT NULL

CONSTRAINT [PK_ID_OTVFACE] PRIMARY KEY CLUSTERED ([ID_OTVFACE] ASC) ON [PRIMARY]
)

--таблица техника
CREATE TABLE TEHNIQ(
ID_TEHNIQ INT IDENTITY(1,1),
FAM_TEHNIQ NVARCHAR(250) NOT NULL,
NAM_TEHNIQ NVARCHAR(250) NOT NULL,
OT_TEHNIQ NVARCHAR(250) NOT NULL,
MAIL_TEHNIQ NVARCHAR(250) NOT NULL,
NUM_TEHNIQ NVARCHAR(15) NOT NULL

CONSTRAINT [PK_ID_TEHNIQ] PRIMARY KEY CLUSTERED ([ID_TEHNIQ] ASC) ON [PRIMARY]
)

--таблица марка огнетушителя
CREATE TABLE  MARK_OGN(
ID_MARK_OGN INT IDENTITY(1,1),
NAM_MARK_OGN NVARCHAR(250) NOT NULL,
NUM_MARK_OGN NVARCHAR(250) NOT NULL

CONSTRAINT [PK_ID_MARK_OGN] PRIMARY KEY CLUSTERED ([ID_MARK_OGN] ASC) ON [PRIMARY]
)

--таблица вид инструктажа
CREATE TABLE TYPE_INSTRUC(
ID_TYPE_INSTRUC INT IDENTITY(1,1),
NAM_TYPE_INSTRUC NVARCHAR(250) NOT NULL

CONSTRAINT [PK_ID_TYPE_INSTRUC] PRIMARY KEY CLUSTERED ([ID_TYPE_INSTRUC] ASC) ON [PRIMARY]
)

 --таблица типа огнетушителя
CREATE TABLE TYPE_OGN(
ID_TYPE_OGN INT IDENTITY(1,1),
NAM_TYPE_OGN NVARCHAR(250) NOT NULL

CONSTRAINT [PK_ID_TYPE_OGN] PRIMARY KEY CLUSTERED ([ID_TYPE_OGN] ASC) ON [PRIMARY]
)

--таблица огнетушителей
CREATE TABLE OGN(
ID_OGN  INT IDENTITY(1,1),
NUM_OGN INT NOT NULL,
DATE_VV_EX DATE,
ZAVOD_NUM NVARCHAR (10) NOT NULL, 
DATE_BORN DATE,
CONSENTRAT NVARCHAR (10),

ID_TYPE_OGN INT NOT NULL,
ID_MARK_OGN INT NOT NULL,
ID_PALAS INT NOT NULL

CONSTRAINT [PK_ID_OGN] PRIMARY KEY CLUSTERED ([ID_OGN] ASC) ON [PRIMARY]
)

ALTER TABLE OGN
ADD CONSTRAINT ID_TYPE_OGN_OGN_FK FOREIGN KEY (ID_TYPE_OGN) REFERENCES TYPE_OGN(ID_TYPE_OGN)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE OGN
ADD CONSTRAINT ID_MARK_OGN_OGN_FK FOREIGN KEY (ID_MARK_OGN) REFERENCES MARK_OGN(ID_MARK_OGN)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE OGN
ADD CONSTRAINT ID_PALAS_OGN_FK FOREIGN KEY (ID_PALAS) REFERENCES PALAS(ID_PALAS)
ON DELETE NO ACTION
ON UPDATE NO ACTION



--таблица журнала учета огнетушителей
CREATE TABLE JUO(
ID_JUO INT IDENTITY(1,1),
DATE_JUO DATE,
NEDOCH_OGN NVARCHAR(MAX) NOT NULL,

ID_TEHNIQ INT NOT NULL,
ID_OTVFACE INT NOT NULL,
ID_TYPE_TO_OGN INT NOT NULL,
ID_OGN INT NOT NULL,
ID_SOS_OGN INT NOT NULL

CONSTRAINT [PK_ID_JUO] PRIMARY KEY CLUSTERED ([ID_JUO] ASC) ON [PRIMARY]
)

ALTER TABLE JUO
ADD CONSTRAINT ID_TEHNIQ_JUO_FK FOREIGN KEY (ID_TEHNIQ) REFERENCES TEHNIQ(ID_TEHNIQ)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JUO
ADD CONSTRAINT ID_OTVFACE_JUO_FK FOREIGN KEY (ID_OTVFACE) REFERENCES OTVFACE(ID_OTVFACE)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JUO
ADD CONSTRAINT ID_TYPE_TO_OGN_JUO_FK FOREIGN KEY (ID_TYPE_TO_OGN) REFERENCES TYPE_TO_OGN(ID_TYPE_TO_OGN)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JUO
ADD CONSTRAINT ID_OGN_JUO_FK FOREIGN KEY (ID_OGN) REFERENCES OGN(ID_OGN)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JUO
ADD CONSTRAINT ID_SOS_OGN_JUO_FK FOREIGN KEY (ID_SOS_OGN) REFERENCES SOS_OGN(ID_SOS_OGN)
ON DELETE NO ACTION
ON UPDATE NO ACTION



--таблица журнала проверки противопожарного состояния помещений перед их закрытием
CREATE TABLE JPPSPPZ(
ID_JPPSPPZ INT IDENTITY(1,1),
DATE_JPPSPPZ DATE,
TIME_JPPSPZ TIME,
NEDOCH NVARCHAR(MAX) NOT NULL,
UST_NEDOCH NVARCHAR(250),

ID_TEHNIQ INT NOT NULL,
ID_PALAS INT NOT NULL

CONSTRAINT [PK_ID_JPPSPPZ] PRIMARY KEY CLUSTERED ([ID_JPPSPPZ] ASC) ON [PRIMARY]
)

ALTER TABLE JPPSPPZ
ADD CONSTRAINT ID_TEHNIQ_JPPSPPZ_FK FOREIGN KEY (ID_TEHNIQ) REFERENCES TEHNIQ(ID_TEHNIQ)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JPPSPPZ
ADD CONSTRAINT ID_PALAS_JPPSPPZ_FK FOREIGN KEY (ID_PALAS) REFERENCES PALAS(ID_PALAS)
ON DELETE NO ACTION
ON UPDATE NO ACTION



--таблица журнал регистрации работ технического обслуживания систем защиты
CREATE TABLE JRRTOSZ(
ID_JRRTOSZ INT IDENTITY(1,1),
DATE_JRRTOSZ DATE, 
OP_RABOT NVARCHAR(MAX) NOT NULL,

ID_STAT_SAVE_SYS INT NOT NULL,
ID_COM_SAVE_SYS INT NOT NULL,
ID_TEHNIQ INT NOT NULL,
ID_OTVFACE INT NOT NULL,
ID_PALAS INT NOT NULL,
ID_TYPE_SAVE_SYS INT NOT NULL,
ID_TYPE_TO INT NOT NULL

CONSTRAINT [PK_ID_JRRTOSZ] PRIMARY KEY CLUSTERED ([ID_JRRTOSZ] ASC) ON [PRIMARY]
)

ALTER TABLE JRRTOSZ
ADD CONSTRAINT ID_STAT_SAVE_SYS_JRRTOSZ_FK FOREIGN KEY (ID_STAT_SAVE_SYS) REFERENCES STAT_SAVE_SYS(ID_STAT_SAVE_SYS)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JRRTOSZ
ADD CONSTRAINT ID_COM_SAVE_SYS_FK FOREIGN KEY (ID_COM_SAVE_SYS) REFERENCES COM_SAVE_SYS(ID_COM_SAVE_SYS)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JRRTOSZ
ADD CONSTRAINT ID_TEHNIQ_JRRTOSZ_FK FOREIGN KEY (ID_TEHNIQ) REFERENCES TEHNIQ(ID_TEHNIQ)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JRRTOSZ
ADD CONSTRAINT ID_OTVFACE_JRRTOSZ_FK FOREIGN KEY (ID_OTVFACE) REFERENCES OTVFACE(ID_OTVFACE)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JRRTOSZ
ADD CONSTRAINT ID_PALAS_JRRTOSZ_FK FOREIGN KEY (ID_PALAS) REFERENCES PALAS(ID_PALAS)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JRRTOSZ
ADD CONSTRAINT ID_TYPE_SAVE_SYS_JRRTOSZ_FK FOREIGN KEY (ID_TYPE_SAVE_SYS) REFERENCES TYPE_SAVE_SYS(ID_TYPE_SAVE_SYS)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JRRTOSZ
ADD CONSTRAINT ID_TYPE_TO_JRRTOSZ_FK FOREIGN KEY (ID_TYPE_TO) REFERENCES TYPE_TO(ID_TYPE_TO)
ON DELETE NO ACTION
ON UPDATE NO ACTION



--таблица журнала по учету противоаварийных, противопожарных тренировок
CREATE TABLE JUPPPT(
ID_JUPPPT INT IDENTITY(1,1),
DATE_JUPPPT DATE,
INSTIN NVARCHAR(250) NOT NULL,
DOLJ_INSTIN NVARCHAR(250) NOT NULL,
INST NVARCHAR(250) NOT NULL,
DOLJ_INST NVARCHAR(250) NOT NULL,

ID_TYPE_INSTRUC INT NOT NULL,
ID_PALAS INT NOT NULL,
ID_OTVFACE INT NOT NULL

CONSTRAINT [PK_ID_JUPPPT] PRIMARY KEY CLUSTERED ([ID_JUPPPT] ASC) ON [PRIMARY]
)

ALTER TABLE JUPPPT
ADD CONSTRAINT ID_TYPE_INSTRUC_FK FOREIGN KEY (ID_TYPE_INSTRUC) REFERENCES TYPE_INSTRUC(ID_TYPE_INSTRUC)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JUPPPT
ADD CONSTRAINT ID_PALAS_FK FOREIGN KEY (ID_PALAS) REFERENCES PALAS(ID_PALAS)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE JUPPPT
ADD CONSTRAINT ID_OTVFACE_JUPPT_FK FOREIGN KEY (ID_OTVFACE) REFERENCES OTVFACE(ID_OTVFACE)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PALAS
ADD CONSTRAINT ID_OTVFACE_FK FOREIGN KEY (ID_OTVFACE) REFERENCES OTVFACE(ID_OTVFACE)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PALAS
ADD CONSTRAINT ID_STAT_SAVE_SYS_FK FOREIGN KEY (ID_STAT_SAVE_SYS) REFERENCES STAT_SAVE_SYS(ID_STAT_SAVE_SYS)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE PALAS
ADD CONSTRAINT ID_SOS_PALASE_FK FOREIGN KEY (ID_SOS_PALASE) REFERENCES SOS_PALASE(ID_SOS_PALASE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
